INFO 2025-08-29 23:15:23,548 autoreload 4776 140671104528640 Watching for file changes with StatReloader
INFO 2025-08-29 23:15:37,182 autoreload 4977 139818768728320 Watching for file changes with StatReloader
ERROR 2025-08-29 23:31:00,765 exception 6780 140315448385792 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-29 23:31:02,073 log 6780 140315448385792 Bad Request: /health/
ERROR 2025-08-29 23:31:02,074 exception 6780 140315448385792 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-29 23:31:02,082 log 6780 140315448385792 Bad Request: /admin/
ERROR 2025-08-29 23:31:02,083 exception 6780 140315448385792 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-29 23:31:02,091 log 6780 140315448385792 Bad Request: /api/v1/accounts/
ERROR 2025-08-29 23:31:02,092 exception 6780 140315448385792 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-29 23:31:02,100 log 6780 140315448385792 Bad Request: /api/v1/students/
ERROR 2025-08-29 23:31:02,100 exception 6780 140315448385792 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-29 23:31:02,109 log 6780 140315448385792 Bad Request: /api/v1/ai-teacher/
ERROR 2025-08-29 23:31:02,110 exception 6780 140315448385792 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-29 23:31:02,118 log 6780 140315448385792 Bad Request: /api/v1/analytics/
INFO 2025-08-30 03:23:20,044 autoreload 13419 139656067391744 Watching for file changes with StatReloader
ERROR 2025-08-30 03:23:38,033 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,257 log 13637 140634023973120 Bad Request: /api/v1/accounts/login/
ERROR 2025-08-30 03:23:39,257 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,265 log 13637 140634023973120 Bad Request: /api/v1/accounts/logout/
ERROR 2025-08-30 03:23:39,266 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,274 log 13637 140634023973120 Bad Request: /api/v1/accounts/profile/
ERROR 2025-08-30 03:23:39,274 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,284 log 13637 140634023973120 Bad Request: /api/v1/students/
ERROR 2025-08-30 03:23:39,284 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,292 log 13637 140634023973120 Bad Request: /api/v1/students/
ERROR 2025-08-30 03:23:39,293 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,301 log 13637 140634023973120 Bad Request: /api/v1/students/1/
ERROR 2025-08-30 03:23:39,301 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,309 log 13637 140634023973120 Bad Request: /api/v1/students/1/
ERROR 2025-08-30 03:23:39,309 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,317 log 13637 140634023973120 Bad Request: /api/v1/students/1/
ERROR 2025-08-30 03:23:39,318 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,325 log 13637 140634023973120 Bad Request: /api/v1/ai-teacher/lessons/
ERROR 2025-08-30 03:23:39,326 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,334 log 13637 140634023973120 Bad Request: /api/v1/ai-teacher/lessons/
ERROR 2025-08-30 03:23:39,334 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,342 log 13637 140634023973120 Bad Request: /api/v1/ai-teacher/lessons/1/
ERROR 2025-08-30 03:23:39,343 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,351 log 13637 140634023973120 Bad Request: /api/v1/ai-teacher/lessons/1/
ERROR 2025-08-30 03:23:39,351 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,359 log 13637 140634023973120 Bad Request: /api/v1/ai-teacher/lessons/1/
ERROR 2025-08-30 03:23:39,359 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,368 log 13637 140634023973120 Bad Request: /api/v1/analytics/
ERROR 2025-08-30 03:23:39,368 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,376 log 13637 140634023973120 Bad Request: /api/v1/analytics/
ERROR 2025-08-30 03:23:39,376 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,385 log 13637 140634023973120 Bad Request: /api/v1/monitoring/
ERROR 2025-08-30 03:23:39,385 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,393 log 13637 140634023973120 Bad Request: /api/v1/monitoring/toggle/
ERROR 2025-08-30 03:23:39,393 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,401 log 13637 140634023973120 Bad Request: /api/v1/monitoring/privacy-settings/
ERROR 2025-08-30 03:23:39,402 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,410 log 13637 140634023973120 Bad Request: /api/v1/families/
ERROR 2025-08-30 03:23:39,410 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,418 log 13637 140634023973120 Bad Request: /api/v1/families/members/
ERROR 2025-08-30 03:23:39,418 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,426 log 13637 140634023973120 Bad Request: /api/v1/families/members/1/
ERROR 2025-08-30 03:23:39,427 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,435 log 13637 140634023973120 Bad Request: /api/v1/staff/
ERROR 2025-08-30 03:23:39,435 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,443 log 13637 140634023973120 Bad Request: /api/v1/staff/
ERROR 2025-08-30 03:23:39,443 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,451 log 13637 140634023973120 Bad Request: /api/v1/staff/1/
ERROR 2025-08-30 03:23:39,451 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,459 log 13637 140634023973120 Bad Request: /api/v1/staff/1/
ERROR 2025-08-30 03:23:39,460 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,467 log 13637 140634023973120 Bad Request: /api/v1/staff/1/
ERROR 2025-08-30 03:23:39,468 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,476 log 13637 140634023973120 Bad Request: /api/v1/lessons/
ERROR 2025-08-30 03:23:39,476 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,484 log 13637 140634023973120 Bad Request: /api/v1/lessons/
ERROR 2025-08-30 03:23:39,484 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,492 log 13637 140634023973120 Bad Request: /api/v1/lessons/1/
ERROR 2025-08-30 03:23:39,493 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,500 log 13637 140634023973120 Bad Request: /api/v1/lessons/1/
ERROR 2025-08-30 03:23:39,501 exception 13637 140634023973120 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-08-30 03:23:39,509 log 13637 140634023973120 Bad Request: /api/v1/lessons/1/
INFO 2025-08-30 03:23:49,896 autoreload 13419 139656067391744 /workspace/ai_school_management/settings.py changed, reloading.
INFO 2025-08-30 03:23:50,530 autoreload 13701 140475675443456 Watching for file changes with StatReloader
INFO 2025-08-30 03:25:38,203 autoreload 14073 140380228276480 Watching for file changes with StatReloader
WARNING 2025-08-30 03:25:43,805 log 14133 140376694841600 Not Found: /api/v1/accounts/login/
WARNING 2025-08-30 03:25:43,808 log 14133 140376694841600 Not Found: /api/v1/accounts/profile/
WARNING 2025-08-30 03:25:43,811 log 14133 140376694841600 Method Not Allowed: /api/v1/students/
WARNING 2025-08-30 03:25:43,812 log 14133 140376694841600 Not Found: /api/v1/students/1/
WARNING 2025-08-30 03:25:43,813 log 14133 140376694841600 Not Found: /api/v1/students/1/
WARNING 2025-08-30 03:25:43,815 log 14133 140376694841600 Not Found: /api/v1/students/1/
WARNING 2025-08-30 03:25:43,818 log 14133 140376694841600 Method Not Allowed: /api/v1/ai-teacher/lessons/
WARNING 2025-08-30 03:25:43,819 log 14133 140376694841600 Not Found: /api/v1/ai-teacher/lessons/1/
WARNING 2025-08-30 03:25:43,820 log 14133 140376694841600 Not Found: /api/v1/ai-teacher/lessons/1/
WARNING 2025-08-30 03:25:43,822 log 14133 140376694841600 Not Found: /api/v1/ai-teacher/lessons/1/
WARNING 2025-08-30 03:25:43,825 log 14133 140376694841600 Not Found: /api/v1/analytics/
WARNING 2025-08-30 03:25:43,827 log 14133 140376694841600 Not Found: /api/v1/analytics/
WARNING 2025-08-30 03:25:43,830 log 14133 140376694841600 Not Found: /api/v1/monitoring/
WARNING 2025-08-30 03:25:43,833 log 14133 140376694841600 Not Found: /api/v1/monitoring/toggle/
WARNING 2025-08-30 03:25:43,836 log 14133 140376694841600 Not Found: /api/v1/monitoring/privacy-settings/
WARNING 2025-08-30 03:25:43,840 log 14133 140376694841600 Not Found: /api/v1/families/members/
WARNING 2025-08-30 03:25:43,842 log 14133 140376694841600 Not Found: /api/v1/families/members/1/
WARNING 2025-08-30 03:25:43,845 log 14133 140376694841600 Method Not Allowed: /api/v1/staff/
WARNING 2025-08-30 03:25:43,846 log 14133 140376694841600 Not Found: /api/v1/staff/1/
WARNING 2025-08-30 03:25:43,847 log 14133 140376694841600 Method Not Allowed: /api/v1/staff/1/
WARNING 2025-08-30 03:25:43,849 log 14133 140376694841600 Not Found: /api/v1/staff/1/
WARNING 2025-08-30 03:25:43,851 log 14133 140376694841600 Method Not Allowed: /api/v1/lessons/
WARNING 2025-08-30 03:25:43,852 log 14133 140376694841600 Not Found: /api/v1/lessons/1/
WARNING 2025-08-30 03:25:43,853 log 14133 140376694841600 Not Found: /api/v1/lessons/1/
WARNING 2025-08-30 03:25:43,855 log 14133 140376694841600 Not Found: /api/v1/lessons/1/
